version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.5.0
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
      - mockauth:mockauth
    volumes:
      - ./config/dispatcher:/config
  deltanotifier:
    image: semtech/mu-delta-notifier
    volumes:
      - ./config/delta:/config
  database:
    image: semtech/mu-authorization
    volumes:
      - ./config/authorization:/config
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
    links:
      - backingTriplestore:triplestore
      - deltanotifier:deltanotifier
  mockauth:
    image: madnificent/mu-mock-access-rights-service
    links:
      - database:database
  backingTriplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - database:database
    volumes:
      - ./config/resources:/config
  musearch:
    image: semtech/mu-search
    links:
      - elasticsearch:elasticsearch
      - database:db
    volumes:
      - ./config/elastic:/config
      - ./data/files:/data
  elasticsearch:
    build: ./elasticsearch-image
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms32g -Xmx32g"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - database:database
    volumes:
      - ./data/files:/share
